# Generated by Django 3.1.3 on 2020-11-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfeature',
            name='value',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='value',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
