# Generated by Django 3.1.3 on 2020-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_auto_20201107_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='value',
            field=models.CharField(default='', max_length=64),
        ),
    ]
