# Generated by Django 3.1.3 on 2020-11-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_auto_20201107_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_app.producttype'),
        ),
    ]
